clear
set more off, perm 
cap log close
global rawdata "C:\Users\Mahofa\OneDrive - University of Cape Town\CurrentWork\APRA\rawdata"
global tmp "C:\Users\Mahofa"
global code "C:\Users\Mahofa\OneDrive - University of Cape Town\CurrentWork\APRA\code"
global output "C:\Users\Mahofa\OneDrive - University of Cape Town\CurrentWork\APRA\output"
global data "C:\Users\Mahofa\OneDrive - University of Cape Town\CurrentWork\APRA\data"

log using "$output\apra_analyse.txt", replace

use "$data\hhdmerged_final", clear
preserve
keep cont_farming1 interview__id hh_a_10__Latitude hh_a_10__Longitude
keep if cont_farming1 == 1
export delimited using "$data\map_mazowe.csv", replace
restore

preserve
keep cont_farming1 interview__id hh_a_10__Latitude hh_a_10__Longitude
keep if cont_farming1 == 0
export delimited using "$data\map_mazowe0.csv", replace
restore

drop adm3_pcode ward hh_a_10__Latitude hh_a_10__Longitude hh_a_04b ag_d_18b ///
hh_z_7f income_module_respondent hh_e_1b hh_e_19b3__* hh_e_24mobile__* ///
hh_e_25b hh_e_26b hh_e_27b hh_e_28b hh_e_29b hh_e_30b hh_e_31b inc_adult_fem ///
hh_f_13b hh_f_23c hh_z_1a hh_z_7a hh_z_7b hh_z_7c ag_d_1b hh_a_28c_oth herb_agro-irr_rt ///
hh_z_1b hh_e_25a-hh_e_31a hh_a_26a hh_a_27a hh_a_28a hh_a_28e hh_e_32-female_inc_avail hh_z_6a ///
hh_a_28b hh_e_19b1__0 hh_e_19b2__0 MPI_class interview__key 
inspect income_source__* hh_e_19a__*
egen nfarminc = rowtotal(income_source__1-income_source__5 hh_e_19a__1-hh_e_19a__10)
recode nfarminc (2/7 = 1)
lab var nfarminc "Non Farm Income"
ren income_source__1 reg_emp
recode foodinsec (0 = 1) (1/9 = 2), g(foodsec)
table foodsec foodinsec
lab define foodsec 1 "food secure" 2 "food insecure"
lab val foodsec foodsec
tab cont_farming1
table contrfarming cont_farming1
recode cont_farming1 (0 = 1) (1 = 2)
lab define cont_farming1 1 "No" 2 "Yes"
lab val cont_farming1 cont_farming1
tab HCI_Quartile
lab define HCI_Quartile 1 "Low" 2 "Medium" 3 "High" 4 "Very High"
lab val HCI_Quartile HCI_Quartile
xtile HCId = HCI, nq(2)
tab HCId
g HCIdum = (HCI>=50)
egen dependent = rowtotal(chdn old)
egen productive = rowtotal(youth adult)
g dpratio = dependent/productive
lab var dpratio "Dependency ratio"
egen prodval = rowtotal(prodassetvalue1 prodassetvalue2 prodassetvalue3 ///
prodassetvalue4 prodassetvalue5 prodassetvalue6 prodassetvalue7 ///
prodassetvalue8 prodassetvalue9 prodassetvalue10 prodassetvalue11)
lab var prodval "Value of productive assets"
egen cassetval = rowtotal(casset_value1 casset_value2 casset_value3 ///
casset_value4 casset_value6 casset_value7 casset_value8 casset_value9 casset_value10)
lab var cassetval "Value of non-productive assets"
encode interview__id, g(interview__id1)
drop interview__id
order interview__id1
ren interview__id1 interview__id
save "$data\hhdmerged_final_analyse", replace
qui ttst1 cont_farming1 1 2, newvars(CFarmer) temp($tmp\) 
table1 cont_farming1 using $tmp\, id(interview__id) order
replace label="Non Farm Income" if variables=="nfarminc"
replace label="Regular employment" if variables=="reg_emp"
replace label="Participation in rental market" if variables=="rentmkt"
replace label="Tenant" if variables=="rent_in"
replace label="Distance to main markets" if variables=="dist"
replace label="Landlord" if variables=="rent_out"
replace label="Area rented in in ha" if variables=="rentin_area"
replace label="Area rented out in ha" if variables=="rentot_area"
replace label="Total area owned" if variables=="land_own"
replace label="Household Commercialisation Index" if variables=="HCI"
replace label="Household dietary diversity" if variables=="HDDS"
replace label="Female household dietary diversity score" if variables=="HDDS_f"
replace label="foodsecurity" if variables=="foodinsec"
replace label="Age of household head in completed years" if variables=="age"
replace label="Years of schooling" if variables=="hh_a_19"
replace label="hh_a_23    out of school" if variables=="hh_a_23"
replace label="All care work (hours)" if variables=="unpd_cre"
replace label="Dependency ratio" if variables=="dpratio"
replace label="Value of productive assets" if variables=="prodval"
replace label="Value of non-productive assets" if variables=="cassetval"
replace label="Cooking/preparing meals (hours)" if variables=="cooking"
replace label="Taking care of young children   " if variables=="chdn_care"
replace label="Collecting firewood" if variables=="cllt_fire"
replace label="Collecting water" if variables=="cllct_wter"
replace label="Household head is male" if variables=="male"
replace label="Female headed household" if variables=="female"
replace label="Monogamously married" if variables=="married3"
replace label="Polygamously married" if variables=="married4"
replace label="Main occupation in Agriculture" if variables=="mainjob2"
replace label="Main occupation in Mining" if variables=="mainjob3"
replace label="Main occupation in Mnufacturing" if variables=="mainjob4"
replace label="hh_a_23==Yes" if variables=="outschool1"
replace label="Household size" if variables=="hhdsize"
replace label="Number of children 0-14" if variables=="chdn"
replace label="Number of female children below the age of 14" if variables=="nofemale"
replace label="Number of male children below the age of 14" if variables=="nomale"
replace label="Number of youth 15-34" if variables=="youth"
replace label="Number of male youth 15-34" if variables=="youthmale"
replace label="Number of female youth 15-34" if variables=="youthfmale"
replace label="Number of adults 35-60" if variables=="adult"
replace label="Adult male aged between 35 and 60" if variables=="adultmale"
replace label="Adult female aged between 35 and 60" if variables=="adultfemale"
replace label="Number of elders" if variables=="old"
replace label="Number of female members aged 60 and above" if variables=="oldfemale"
replace label="Number of male members aged 60 and above" if variables=="oldmale"
replace label="Male total days worked on land preparation & planting" if variables=="lndppmale"
replace label="Female total days worked on land preparation & planting" if variables=="lndppfmale"
replace label="Male total days worked on nursery & seedbed mmgt" if variables=="ag_b_nsm1"
replace label="Female total days worked on nursery & seedbed mmgt" if variables=="ag_b_nsm2"
replace label="Male total days worked in irrigation and drainage" if variables=="ag_b_ird1"
replace label="Female total days worked in irrigation and drainage" if variables=="ag_b_ird2"
replace label="Male total days worked weeding" if variables=="weeding1"
replace label="Female total days worked weeding" if variables=="weeding2"
replace label="Male total days worked on applying fert" if variables=="app_fert1"
replace label="Female total days worked on applying fer" if variables=="app_fert2"
replace label="Male total days worked on applying agrochem" if variables=="app_chem1"
replace label="Female total days worked on applying agrochem" if variables=="app_chem2"
replace label="Male total days worked on harvesting" if variables=="harve1"
replace label="Female total days worked on harvesting" if variables=="harve2"
replace label="Male total days worked curing" if variables=="curing1"
replace label="Female total days worked curing" if variables=="curing2"
replace label="Male total days worked on grading & packaging" if variables=="grading1"
replace label="Female total days worked on grading & packagin" if variables=="grading2"
replace label="Total costs incurred on herbicides" if variables=="herbcost"
replace label="Total costs incurred on pesticides" if variables=="pestcost"
replace label="Tobacco fuel curing costs" if variables=="tcuringcost"
replace label="Irrigation costs" if variables=="irrcost"
replace label="Distance to tarmac" if variables=="dist_trd"
replace label="Time to tarmac road in hours" if variables=="tim_trd"
replace label="Walking to tarmarc road" if variables=="mode11"
replace label="Bike to tarmac road" if variables=="mode21"
replace label="Oxcart to tarmac road" if variables=="mode31"
replace label="Canoe to tarmac road" if variables=="mode41"
replace label="Motor to tarmac road" if variables=="mode51"
replace label="Distance to all weather road" if variables=="dist_wrd"
replace label="Time to all weather road in hours" if variables=="tim_wrd"
replace label="Walking to all wether road" if variables=="mode12"
replace label="Bike to all wether road" if variables=="mode22"
replace label="Oxcart to all wether road" if variables=="mode32"
replace label="Canoe to all wether road" if variables=="mode42"
replace label="Motor to all wether road" if variables=="mode52"
replace label="Distance to feeder road" if variables=="dist_frd"
replace label="Time to feeder road in hours" if variables=="tim_frd"
replace label="Walking to feeder road" if variables=="mode13"
replace label="Bike to feeder road" if variables=="mode23"
replace label="Oxcart to feeder road" if variables=="mode33"
replace label="Canoe to feeder road" if variables=="mode43"
replace label="Motor to feeder road" if variables=="mode53"
replace label="Distance to agro-dealers" if variables=="dist_agd"
replace label="Time to agro-dealers in hours" if variables=="tim_agd"
replace label="Walking to agro-dealers" if variables=="mode14"
replace label="Bike to agro-dealers" if variables=="mode24"
replace label="Oxcart to agro-dealers" if variables=="mode34"
replace label="Canoe to agro-dealers" if variables=="mode44"
replace label="Motor to agro-dealers" if variables=="mode54"
replace label="Distance to established market place" if variables=="dist_mkp"
replace label="Time to established market place in hours" if variables=="tim_mkp"
replace label="Walking to market place" if variables=="mode15"
replace label="Bike to market place" if variables=="mode25"
replace label="Oxcart to market place" if variables=="mode35"
replace label="Canoe to market place" if variables=="mode45"
replace label="Motor to market place" if variables=="mode55"
replace label="Distance to livestock market" if variables=="dist_lmkt"
replace label="Time to livestock market in hours" if variables=="tim_lmkt"
replace label="Walking to livestock market place" if variables=="mode16"
replace label="Bike to livestock market place" if variables=="mode26"
replace label="Oxcart to livestock market place" if variables=="mode36"
replace label="Canoe to livestock market place" if variables=="mode46"
replace label="Motor to livestock market place" if variables=="mode56"
replace label="Distance to agricultural exetension services" if variables=="dist_ext"
replace label="Time to agricultural exetension services in hours" if variables=="tim_ext"
replace label="Walking to extension offices" if variables=="mode17"
replace label="Bike to extension offices" if variables=="mode27"
replace label="Oxcart to extension offices" if variables=="mode37"
replace label="Canoe to extension offices" if variables=="mode47"
replace label="Motor to extension offices" if variables=="mode57"
replace label="Distance to vet" if variables=="dist_vet"
replace label="Time to vet in hours" if variables=="tim_vet"
replace label="Walking to veterinary clinic" if variables=="mode18"
replace label="Bike to veterinary clinic" if variables=="mode28"
replace label="Oxcart to veterinary clinic" if variables=="mode38"
replace label="Canoe to veterinary clinic" if variables=="mode48"
replace label="Motor to veterinary clinic" if variables=="mode58"
replace label="Distance to artificial insemination services" if variables=="dist_ais"
replace label="Time to artificial insemination services in hours" if variables=="tim_ais"
replace label="Walking to artificial insemination services" if variables=="mode19"
replace label="Bike to artificial insemination services" if variables=="mode29"
replace label="Oxcart to artificial insemination services" if variables=="mode39"
replace label="Canoe to artificial insemination services" if variables=="mode49"
replace label="Motor to artificial insemination services" if variables=="mode59"
replace label="Distance to tillage services" if variables=="dist_till"
replace label="Time to tillage services in hours" if variables=="tim_till"
replace label="Walking to tillage services" if variables=="mode110"
replace label="Bike to tillage services" if variables=="mode210"
replace label="Oxcart to tillage services" if variables=="mode310"
replace label="Canoe to tillage services" if variables=="mode410"
replace label="Motor to tillage services" if variables=="mode510"
replace label="Distance to village centre" if variables=="dist_villcentr"
replace label="Time to village centre in hours" if variables=="tim_villcentr"
replace label="Walking to village centre" if variables=="mode113"
replace label="Bike to village centre" if variables=="mode213"
replace label="Oxcart to village centre" if variables=="mode313"
replace label="Canoe to village centre" if variables=="mode413"
replace label="Motor to village centre" if variables=="mode513"
replace label="Number of traders" if variables=="no_trder"
replace label="relation headman:Blood tie" if variables=="hh_a_25b__1"
replace label="relation headman:Marital tie" if variables=="hh_a_25b__2"
replace label="relation headman:Friendship tie" if variables=="hh_a_25b__3"
replace label="relation headman:Clan tie" if variables=="hh_a_25b__4"
replace label="relation headman spouse:Blood tie" if variables=="hh_a_26b__1"
replace label="relation headman spouse:Marital tie" if variables=="hh_a_26b__2"
replace label="relation headman spouse:Friendship tie" if variables=="hh_a_26b__3"
replace label="relation headman spouse:Clan tie" if variables=="hh_a_26b__4"
replace label="chief relation:Blood tie" if variables=="hh_a_27b__1"
replace label="chief relation:Marital tie" if variables=="hh_a_27b__2"
replace label="chief relation:Friendship tie" if variables=="hh_a_27b__3"
replace label="chief relation:Clan tie" if variables=="hh_a_27b__4"
replace label="mobile money serv:Sending money" if variables=="hh_a_28c__1"
replace label="mobile money serv:Receiving money" if variables=="hh_a_28c__2"
replace label="mobile money serv:Payments (E.g.Paying bills)" if variables=="hh_a_28c__3"
replace label="mobile money serv:Other" if variables=="hh_a_28c__4"
replace label="frequency mobile money" if variables=="hh_a_28d"
replace label="agri services:Tarmac/tarred road" if variables=="hh_a_29a__1"
replace label="agri services:All-weather roads" if variables=="hh_a_29a__2"
replace label="agri services:Feeder road" if variables=="hh_a_29a__3"
replace label="agri services:Agro-dealers (seed, fertlilizer,agrochemicals)" if variables=="hh_a_29a__4"
replace label="agri services:Established market place with many buyers and sellers locally" if variables=="hh_a_29a__5"
replace label="agri services:Point where you can sell livestock/livestock products to private buyers" if variables=="hh_a_29a__6"
replace label="agri services:Agricultural extension offices" if variables=="hh_a_29a__7"
replace label="agri services:Veterinary clinics/Para Vets" if variables=="hh_a_29a__8"
replace label="agri services:Artificial Insemination (AI) service providers" if variables=="hh_a_29a__9"
replace label="agri services:Tillage services (tractors)" if variables=="hh_a_29a__10"
replace label="agri services:Village Centre" if variables=="hh_a_29a__13"
replace label="Raised cattle" if variables=="ag_d_1a__1"
replace label="Raised goats" if variables=="ag_d_1a__2"
replace label="Raised sheep" if variables=="ag_d_1a__3"
replace label="Raised pigs" if variables=="ag_d_1a__4"
replace label="Raised Poultry" if variables=="ag_d_1a__5"
replace label="Raised Donkeys" if variables=="ag_d_1a__6"
replace label="Raised other livestock" if variables=="ag_d_1a__7"
replace label="livestock produce:Milk" if variables=="ag_d_18a__1"
replace label="livestock produce:Eggs" if variables=="ag_d_18a__2"
replace label="livestock produce:Meat" if variables=="ag_d_18a__3"
replace label="livestock produce:Hiring-out livestock service" if variables=="ag_d_18a__4"
replace label="livestock produce:Other" if variables=="ag_d_18a__5"
replace label="Years under contract farming" if variables=="hh_z_2"
replace label="crops contracted:Maize" if variables=="hh_z_3__1"
replace label="crops contracted:Tobacco" if variables=="hh_z_3__2"
replace label="crops contracted:Groundnut" if variables=="hh_z_3__3"
replace label="crops contracted:Wheat" if variables=="hh_z_3__4"
replace label="crops contracted:Barley" if variables=="hh_z_3__5"
replace label="crops contracted:Cowpeas" if variables=="hh_z_3__6"
replace label="crops contracted:Common Beans" if variables=="hh_z_3__7"
replace label="crops contracted:Soya Beans" if variables=="hh_z_3__8"
replace label="crops contracted:Sorghum" if variables=="hh_z_3__9"
replace label="crops contracted:Rice" if variables=="hh_z_3__10"
replace label="crops contracted:Irish Potato" if variables=="hh_z_3__11"
replace label="crops contracted:Sweet Potato" if variables=="hh_z_3__12"
replace label="crops contracted:Onions" if variables=="hh_z_3__13"
replace label="crops contracted:Pepper" if variables=="hh_z_3__14"
replace label="crops contracted:Tomato" if variables=="hh_z_3__15"
replace label="crops contracted:Cabbage" if variables=="hh_z_3__16"
replace label="crops contracted:Butternut" if variables=="hh_z_3__17"
replace label="crops contracted:Vegetables (Covo/Rape)" if variables=="hh_z_3__18"
replace label="crops contracted:Sunflower" if variables=="hh_z_3__21"
replace label="Extension frequency" if variables=="hh_z_5b"
replace label="info source:Radio/TV" if variables=="hh_z_6b__1"
replace label="info source:Extension Officers" if variables=="hh_z_6b__2"
replace label="info source:Mobile platforms" if variables=="hh_z_6b__3"
replace label="info source:Traders/Contractors" if variables=="hh_z_6b__4"
replace label="info source:Neighbors" if variables=="hh_z_6b__5"
replace label="info source:Others" if variables=="hh_z_6b__6"
replace label="loan use:Purchase inputs" if variables=="hh_z_7d__1"
replace label="loan use:Purchase livestock" if variables=="hh_z_7d__2"
replace label="loan use:Purchase farm machinery" if variables=="hh_z_7d__3"
replace label="loan use:Rent-in land" if variables=="hh_z_7d__4"
replace label="loan use:Hired labor" if variables=="hh_z_7d__5"
replace label="loan use:Others" if variables=="hh_z_7d__6"
replace label="loan reject:Didn't need a loan/credit" if variables=="hh_z_7e__1"
replace label="loan reject:High interest rates" if variables=="hh_z_7e__2"
replace label="loan reject:Lengthy application process" if variables=="hh_z_7e__3"
replace label="loan reject:No lending institution available" if variables=="hh_z_7e__4"
replace label="loan reject:Other" if variables=="hh_z_7e__5"
replace label="overall income sources:Regular employment" if variables=="income_source~1"
replace label="overall income sources:Casual Labour" if variables=="income_source~2"
replace label="overall income sources:Household Enterprises" if variables=="income_source~3"
replace label="overall income sources:Gifts, incl. remittances" if variables=="income_source~4"
replace label="overall income sources:Social transfers" if variables=="income_source~5"
replace label="regular employ sources:Teacher" if variables=="hh_e_1a__1"
replace label="regular employ sources:Shop worker" if variables=="hh_e_1a__2"
replace label="regular employ sources:Processing plant" if variables=="hh_e_1a__3"
replace label="regular employ sources:Long-Term Hired Farm Labour" if variables=="hh_e_1a__4"
replace label="regular employ sources:Civil Servant" if variables=="hh_e_1a__5"
replace label="regular employ sources:Others" if variables=="hh_e_1a__6"
replace label="casual employ:Other Farms" if variables=="hh_e_9__1"
replace label="casual employ:Non-Farm Activity" if variables=="hh_e_9__2"
replace label="other inc sources:Investment income, interest from savings" if variables=="hh_e_19a__1"
replace label="other inc sources:Pension" if variables=="hh_e_19a__2"
replace label="other inc sources:Rental of property/ machinery (including farm land rental)" if variables=="hh_e_19a__3"
replace label="other inc sources:Gifts" if variables=="hh_e_19a__4"
replace label="other inc sources:Free food/maize distribution" if variables=="hh_e_19a__5"
replace label="other inc sources:Food-for-work programme or cash-for work programme" if variables=="hh_e_19a__6"
replace label="other inc sources:Input Subsidy Vouchers" if variables=="hh_e_19a__7"
replace label="other inc sources:Direct cash transfers (from government)" if variables=="hh_e_19a__8"
replace label="other inc sources:Other safety net programme" if variables=="hh_e_19a__9"
replace label="other inc sources:Others" if variables=="hh_e_19a__10"
replace label="other inc sources inc" if variables=="other_inc"
replace label="How many months was income received" if variables=="hh_e_21a1"
replace label="Month when income was received:Jan" if variables=="hh_e_21b1__1"
replace label="Month when income was received:Feb" if variables=="hh_e_21b1__2"
replace label="Month when income was received:March" if variables=="hh_e_21b1__3"
replace label="Month when income was received:April" if variables=="hh_e_21b1__4"
replace label="Month when income was received:May" if variables=="hh_e_21b1__5"
replace label="Month when income was received:June" if variables=="hh_e_21b1__6"
replace label="Month when income was received:July" if variables=="hh_e_21b1__7"
replace label="Month when income was received:Aug" if variables=="hh_e_21b1__8"
replace label="Month when income was received:Sep" if variables=="hh_e_21b1__9"
replace label="Month when income was received:Oct" if variables=="hh_e_21b1__10"
replace label="Month when income was received:Nov" if variables=="hh_e_21b1__11"
replace label="Month when income was received:Dec" if variables=="hh_e_21b1__12"
replace label="other inc sources month high inc" if variables=="hh_e_21d1"
replace label="other inc sources cost" if variables=="hh_e_22_1"
replace label="Obtained income from the following sources as gifts:Cash" if variables=="hh_e_19a2__1"
replace label="Obtained income from the following sources as gifts:Food" if variables=="hh_e_19a2__2"
replace label="Total income received as gift income" if variables=="hh_e_20_2"
replace label="How many months was income received from this source" if variables=="hh_e_21a2"
replace label="Month when inc was received:Jan" if variables=="hh_e_21b2__1"
replace label="Month when income was received:Feb" if variables=="hh_e_21b2__2"
replace label="Month when income was received:March" if variables=="hh_e_21b2__3"
replace label="Month when income was received:April" if variables=="hh_e_21b2__4"
replace label="Month when income was received:May" if variables=="hh_e_21b2__5"
replace label="Month when income was received:June" if variables=="hh_e_21b2__6"
replace label="Month when income was received:July" if variables=="hh_e_21b2__7"
replace label="Month when income was received:Aug" if variables=="hh_e_21b2__8"
replace label="Month when income was received:Sep" if variables=="hh_e_21b2__9"
replace label="Month when income was received:Oct" if variables=="hh_e_21b2__10"
replace label="Month when income was received:Nov" if variables=="hh_e_21b2__11"
replace label="Month when income was received:Dec" if variables=="hh_e_21b2__12"
replace label="gift inc months high inc" if variables=="hh_e_21d2"
replace label="gift inc cost" if variables=="hh_e_22_2"
replace label="own production assets:Hoe" if variables=="hh_e_23a__1"
replace label="own production assets:Spade" if variables=="hh_e_23a__2"
replace label="own production assets:Axe" if variables=="hh_e_23a__3"
replace label="own production assets:Sickle" if variables=="hh_e_23a__4"
replace label="own production assets:Shears" if variables=="hh_e_23a__5"
replace label="own production assets:Knife" if variables=="hh_e_23a__6"
replace label="own production assets:Animal cart" if variables=="hh_e_23a__7"
replace label="own production assets:Plow/Harrow" if variables=="hh_e_23a__8"
replace label="own production assets:Sprayer" if variables=="hh_e_23a__9"
replace label="own production assets:Water Pump" if variables=="hh_e_23a__10"
replace label="own production assets:Tractor" if variables=="hh_e_23a__11"
replace label="own consumer durable assets:Mattress" if variables=="hh_e_24a__1"
replace label="own consumer durable assets:Stove" if variables=="hh_e_24a__2"
replace label="own consumer durable assets:Radio" if variables=="hh_e_24a__3"
replace label="own consumer durable assets:Television" if variables=="hh_e_24a__4"
replace label="own consumer durable assets:Telephone/Landline" if variables=="hh_e_24a__5"
replace label="own consumer durable assets:Mobile phone" if variables=="hh_e_24a__6"
replace label="own consumer durable assets:Fridge" if variables=="hh_e_24a__7"
replace label="own consumer durable assets:Bicycle" if variables=="hh_e_24a__8"
replace label="own consumer durable assets:Motorcycle" if variables=="hh_e_24a__9"
replace label="own consumer durable assets:Car/Truck" if variables=="hh_e_24a__10"
replace label="female regular inc sources:Teacher" if variables=="hh_f_13__1"
replace label="female regular inc sources:Shop worker" if variables=="hh_f_13__2"
replace label="female regular inc sources:Processing plant" if variables=="hh_f_13__3"
replace label="female regular inc sources:Long-Term Hired Farm Labour" if variables=="hh_f_13__4"
replace label="female regular inc sources:Civil Servant" if variables=="hh_f_13__5"
replace label="female regular inc sources:Others" if variables=="hh_f_13__6"
replace label="female causal inc sources:Other Farms" if variables=="hh_f_21__1"
replace label="female causal inc sources:Non-Farm Activity" if variables=="hh_f_21__2"
replace label="Related to headman" if variables=="headman_rel2"
replace label="Spouse related to headman" if variables=="hdmansp_rel2"
replace label="Related to chief" if variables=="chiefrel2"
replace label="Used mobile money in the past 12 months" if variables=="mobile_money2"
replace label="If the hhd head/adult female used mobile money services, did their spouse know" if variables=="mbmney_inf2"
replace label="Where you engaged in contract farming" if variables=="cont_farming1"
replace label="hh_z_1a==Yes" if variables==""
replace label="Received extension services" if variables=="ext1"
replace label="Did you get market information on your produce" if variables=="minfo1"
replace label="Did  you apply for a loan/credit" if variables=="credit1"
replace label="Were you successful in obtaining loan" if variables=="getloan1"
replace label="The richest in the village" if variables=="hhsstatus1"
replace label="Amongst the richest in the village" if variables=="hhsstatus2"
replace label="Richer than most households" if variables=="hhsstatus3"
replace label="About average" if variables=="hhsstatus4"
replace label="A little poorer than most households" if variables=="hhsstatus5"
replace label="Amongst the poorest in the village" if variables=="hhsstatus6"
replace label="The poorest in the village" if variables=="hhsstatus7"
replace label="Very rich" if variables=="hhcircum1"
replace label="Rich" if variables=="hhcircum2"
replace label="Comfortable" if variables=="hhcircum3"
replace label="Can manage to get by" if variables=="hhcircum4"
replace label="Never have quite enough" if variables=="hhcircum5"
replace label="Poor" if variables=="hhcircum6"
replace label="Destitute" if variables=="hhcircum7"
replace label="Not applicable" if variables=="hhdistat1"
replace label="It was more than adequate for the family’s needs" if variables=="hhdistat2"
replace label="It was just adequate for the family’s needs" if variables=="hhdistat3"
replace label="It was less than adequate for the family’s needs" if variables=="hhdistat4"
replace label="Doing well = Able to meet household needs by own efforts" if variables=="hhdwbeing1"
replace label="Doing just okay = Able to meet household needs by own effort" if variables=="hhdwbeing2"
replace label="Struggling = Managing to meet household needs but by depleting production" if variables=="hhdwbeing3"
replace label="Unable to meet household needs, dependent on support from the community" if variables=="hhdwbeing4"
replace label="Has hhd enterprise" if variables=="hhd_ent1"
replace label="No roof" if variables=="roof_noroof"
replace label="Grass roof" if variables=="roof_grass"
replace label="Mud roof" if variables=="roof_mud"
replace label="Stone roof" if variables=="roof_stone"
replace label="Plastic roof" if variables=="roof_plastic"
replace label="Corrugated roof" if variables=="roof_corrugated"
replace label="Wood roof" if variables=="roof_wood"
replace label="Cement Roof" if variables=="roof_cement"
replace label="Other roof" if variables=="roof_other"
replace label="Asbestos roof" if variables=="roof_Asbestos"
replace label="Wall_nowall" if variables=="Wall_nowall"
replace label="Wall_grass" if variables=="Wall_grass"
replace label="Wall_dirt" if variables=="Wall_dirt"
replace label="Wall_woodbamboo" if variables=="Wall_woodbamboo"
replace label="Wall_stone" if variables=="Wall_stone"
replace label="Wall_Concrete~t" if variables=="Wall_Concrete~t"
replace label="Wall_Cement" if variables=="Wall_Cement"
replace label="Wall_Woodplanks" if variables=="Wall_Woodplanks"
replace label="Wall_TiledBri~s" if variables=="Wall_TiledBri~s"
replace label="Wall_Others" if variables=="Wall_Others"
replace label="floor_dirt" if variables=="floor_dirt"
replace label="floor_cowdung" if variables=="floor_cowdung"
replace label="floor_cowdung~l" if variables=="floor_cowdung~l"
replace label="floor_stone" if variables=="floor_stone"
replace label="floor_concrete" if variables=="floor_concrete"
replace label="floor_cement" if variables=="floor_cement"
replace label="floor_woodpla~s" if variables=="floor_woodpla~s"
replace label="floor_tiledbr~s" if variables=="floor_tiledbr~s"
replace label="floor_other" if variables=="floor_other"
replace label="toilet_nofaci~y" if variables=="toilet_nofaci~y"
replace label="toilet_panbuc~t" if variables=="toilet_panbuc~t"
replace label="toilet_pitlat~e" if variables=="toilet_pitlat~e"
replace label="toilet_ventil~d" if variables=="toilet_ventil~d"
replace label="toilet_flush" if variables=="toilet_flush"
replace label="toilet_other" if variables=="toilet_other"
replace label="cookingfuel_D~s" if variables=="cookingfuel_D~s"
replace label="cookingfuel_d~g" if variables=="cookingfuel_d~g"
replace label="cookingfuel_f~d" if variables=="cookingfuel_f~d"
replace label="cookingfuel_c~l" if variables=="cookingfuel_c~l"
replace label="cookingfuel_p~n" if variables=="cookingfuel_p~n"
replace label="cookingfuel_e~y" if variables=="cookingfuel_e~y"
replace label="cookingfuel_gas" if variables=="cookingfuel_gas"
replace label="cookingfuel_s~r" if variables=="cookingfuel_s~r"
replace label="cookingfuel_o~r" if variables=="cookingfuel_o~r"
replace label="Water_natural" if variables=="Water_natural"
replace label="Water_unprote~l" if variables=="Water_unprote~l"
replace label="Water_protect~l" if variables=="Water_protect~l"
replace label="Water_pipedsu~y" if variables=="Water_pipedsu~y"
replace label="Water_other" if variables=="Water_other"
replace label="Water_Borehole" if variables=="Water_Borehole"
replace label="Lighting_grass" if variables=="Lighting_grass"
replace label="Lighting_cand~s" if variables=="Lighting_cand~s"
replace label="Lighting_fire~d" if variables=="Lighting_fire~d"
replace label="Lighting_char~l" if variables=="Lighting_char~l"
replace label="Lighting_para~n" if variables=="Lighting_para~n"
replace label="Lighting_elec~y" if variables=="Lighting_elec~y"
replace label="Lighting_gas" if variables=="Lighting_gas"
replace label="Lighting_solar" if variables=="Lighting_solar"
replace label="Lighting_other" if variables=="Lighting_other"
replace label="Lighting_Noso~e" if variables=="Lighting_Noso~e"
replace label="Lighting_Torch" if variables=="Lighting_Torch"
replace label="Scores for component 1" if variables=="WealthIndex"
replace label="3 quantiles of WealthIndex" if variables=="WealthClass"
replace label="Scores for component 1" if variables=="ProductionAss~x"
replace label="3 quantiles of ProductionAssetIndex" if variables=="ProductionAss~s"
replace label="               " if variables=="ChildDeath"
replace label="               " if variables=="Malnourished"
replace label="               " if variables=="NoElectricity"
replace label="               " if variables=="UnimprovedSan~n"
replace label="               " if variables=="UnsafeDrinkin~r"
replace label="               " if variables=="UnImprovedFloor"
replace label="               " if variables=="UnimprovedCoo~l"
replace label="* see notes" if variables=="NumberDurable~s"
replace label="               " if variables=="AssetsDeprived"
replace label="* see notes" if variables=="outschool"
replace label="* see notes" if variables=="no5years"
replace label="               " if variables=="OutofSchool"
replace label="               " if variables=="LackSchooling"
replace label="mpi: Multidimensional deprivation score" if variables=="MPI_score"
replace label="HCI_Quartile" if variables=="HCI_Quartile"
replace label="4 quantiles of HCI" if variables==""
replace label="4 quantiles of WealthIndex" if variables=="WealthClass4"
replace label="5 quantiles of WealthIndex" if variables=="WealthClass5"
replace label="female causal inc terms:Free Meals" if variables=="hh_f_23a__1"
replace label="female causal inc terms:Shower/Toilet Facilities" if variables=="hh_f_23a__2"
replace label="female causal inc terms:Protection Equipment" if variables=="hh_f_23a__3"
replace label="female causal inc pay:Daily" if variables=="hh_f_23b__1"
replace label="female causal inc pay:Task" if variables=="hh_f_23b__2"
replace label="female causal inc pay:Piece-Rate" if variables=="hh_f_23b__3"
replace label="female causal inc pay:Other" if variables=="hh_f_23b__4"
replace label="casual female piece" if variables=="hh_f_23d"
replace label="female causal inc task" if variables=="hh_f_23d_task"
replace label="hh_f_22==Smallholder(Less than 10ha)" if variables=="farm_emp1"
replace label="hh_f_22==Large-scale(More than 100ha)" if variables=="farm_emp2"
replace label="(sum) hh_e_12" if variables=="hh_e_12"
replace label="(sum) hh_e_12b" if variables=="hh_e_12b"
replace label="(sum) hh_e_13" if variables=="hh_e_13"
replace label="(sum) hh_f_24" if variables=="hh_f_24"
replace label="(sum) hh_f_24b" if variables=="hh_f_24b"
replace label="(sum) hh_f_25" if variables=="hh_f_25"
replace label="Mattress owned" if variables=="casset_owned1"
replace label="Mattress_value" if variables=="casset_value1"
replace label="Stove owned" if variables=="casset_owned2"
replace label="Stove_value" if variables=="casset_value2"
replace label="Radio_owned" if variables=="casset_owned3"
replace label="Radio_value" if variables=="casset_value3"
replace label="Television_owned" if variables=="casset_owned4"
replace label="Television_value" if variables=="casset_value4"
replace label="Mobile phone owned" if variables=="casset_owned6"
replace label="Mobile phone value" if variables=="casset_value6"
replace label="Fridge_owned" if variables=="casset_owned7"
replace label="Fridge_value" if variables=="casset_value7"
replace label="Bicycle owned" if variables=="casset_owned8"
replace label="Bicycle value" if variables=="casset_value8"
replace label="Motor cycle owned" if variables=="casset_owned9"
replace label="Motorcycle_value" if variables=="casset_value9"
replace label="Car/truck_owned" if variables=="casset_owned10"
replace label="Car/truck_value" if variables=="casset_value10"
replace label="1 hh_z_4a" if variables=="hh_z_4a1"
replace label="1 hh_z_4e__1" if variables=="hh_z_4e__11"
replace label="1 hh_z_4e__2" if variables=="hh_z_4e__21"
replace label="1 hh_z_4e__3" if variables=="hh_z_4e__31"
replace label="1 hh_z_4e__4" if variables=="hh_z_4e__41"
replace label="1 hh_z_4e__5" if variables=="hh_z_4e__51"
replace label="1 hh_z_4e__6" if variables=="hh_z_4e__61"
replace label="1 hh_z_4e__7" if variables=="hh_z_4e__71"
replace label="1 hh_z_4e__8" if variables=="hh_z_4e__81"
replace label="2 hh_z_4a" if variables=="hh_z_4a2"
replace label="2 hh_z_4e__1" if variables=="hh_z_4e__12"
replace label="2 hh_z_4e__2" if variables=="hh_z_4e__22"
replace label="2 hh_z_4e__3" if variables=="hh_z_4e__32"
replace label="2 hh_z_4e__4" if variables=="hh_z_4e__42"
replace label="2 hh_z_4e__5" if variables=="hh_z_4e__52"
replace label="2 hh_z_4e__6" if variables=="hh_z_4e__62"
replace label="2 hh_z_4e__7" if variables=="hh_z_4e__72"
replace label="2 hh_z_4e__8" if variables=="hh_z_4e__82"
replace label="8 hh_z_4a" if variables=="hh_z_4a8"
replace label="8 hh_z_4e__1" if variables=="hh_z_4e__18"
replace label="8 hh_z_4e__2" if variables=="hh_z_4e__28"
replace label="8 hh_z_4e__3" if variables=="hh_z_4e__38"
replace label="8 hh_z_4e__4" if variables=="hh_z_4e__48"
replace label="8 hh_z_4e__5" if variables=="hh_z_4e__58"
replace label="8 hh_z_4e__6" if variables=="hh_z_4e__68"
replace label="8 hh_z_4e__7" if variables=="hh_z_4e__78"
replace label="8 hh_z_4e__8" if variables=="hh_z_4e__88"
replace label="12 hh_z_4a" if variables=="hh_z_4a12"
replace label="12 hh_z_4e__1" if variables=="hh_z_4e__112"
replace label="12 hh_z_4e__2" if variables=="hh_z_4e__212"
replace label="12 hh_z_4e__3" if variables=="hh_z_4e__312"
replace label="12 hh_z_4e__4" if variables=="hh_z_4e__412"
replace label="12 hh_z_4e__5" if variables=="hh_z_4e__512"
replace label="12 hh_z_4e__6" if variables=="hh_z_4e__612"
replace label="12 hh_z_4e__7" if variables=="hh_z_4e__712"
replace label="12 hh_z_4e__8" if variables=="hh_z_4e__812"
replace label="NumberMainCrops" if variables=="NumberMainCrops"
replace label="               " if variables=="_ag_b_28b1"
replace label="               " if variables=="_ag_b_28d1"
replace label="               " if variables=="_ag_b_28b2"
replace label="               " if variables=="_ag_b_28d2"
replace label="               " if variables=="_fert_source11"
replace label="               " if variables=="_fert_source21"
replace label="               " if variables=="_fert_source31"
replace label="               " if variables=="_fert_source41"
replace label="               " if variables=="_fert_source12"
replace label="               " if variables=="_fert_source22"
replace label="               " if variables=="_fert_source32"
replace label="               " if variables=="_fert_source42"
replace label="1 hh_e_16" if variables=="hh_e_161"
replace label="1 hh_e_17a" if variables=="hh_e_17a1"
replace label="1 hh_e_17d" if variables=="hh_e_17d1"
replace label="1 hh_e_18" if variables=="hh_e_181"
replace label="hh_a_14==Male" if variables=="gend_ent1"
replace label="hh_a_14==Female" if variables=="gend_ent2"
replace label="liv_sales" if variables=="liv_sales"
replace label="cattleraised" if variables=="cattleraised"
replace label="cattleowned" if variables=="cattleowned"
replace label="cattlevalue" if variables=="cattlevalue"
replace label="cattleslaught~d" if variables=="cattleslaught~d"
replace label="cattlepurchased" if variables=="cattlepurchased"
replace label="cattleprice" if variables=="cattleprice"
replace label="cattledeath" if variables=="cattledeath"
replace label="goatsraised" if variables=="goatsraised"
replace label="goatsowned" if variables=="goatsowned"
replace label="goatsvalue" if variables=="goatsvalue"
replace label="goatsslaughte~d" if variables=="goatsslaughte~d"
replace label="goatspurchased" if variables=="goatspurchased"
replace label="goatsprice" if variables=="goatsprice"
replace label="goatsdeath" if variables=="goatsdeath"
replace label="sheepraised" if variables=="sheepraised"
replace label="sheepowned" if variables=="sheepowned"
replace label="sheepvalue" if variables=="sheepvalue"
replace label="sheepslaughte~d" if variables=="sheepslaughte~d"
replace label="sheeppurchased" if variables=="sheeppurchased"
replace label="sheepprice" if variables=="sheepprice"
replace label="sheepdeath" if variables=="sheepdeath"
replace label="pigsraised" if variables=="pigsraised"
replace label="pigsowned" if variables=="pigsowned"
replace label="pigsvalue" if variables=="pigsvalue"
replace label="pigsslaughtered" if variables=="pigsslaughtered"
replace label="pigspurchased" if variables=="pigspurchased"
replace label="pigsprice" if variables=="pigsprice"
replace label="pigsdeath" if variables=="pigsdeath"
replace label="poultryraised" if variables=="poultryraised"
replace label="poultryowned" if variables=="poultryowned"
replace label="poultryvalue" if variables=="poultryvalue"
replace label="poultryslaugh~d" if variables=="poultryslaugh~d"
replace label="poultrypurcha~d" if variables=="poultrypurcha~d"
replace label="poutryprice" if variables=="poutryprice"
replace label="poultrydeath" if variables=="poultrydeath"
replace label="donkeyraised" if variables=="donkeyraised"
replace label="donkeyowned" if variables=="donkeyowned"
replace label="donkeyvalue" if variables=="donkeyvalue"
replace label="donkeyslaught~d" if variables=="donkeyslaught~d"
replace label="donkeypurchased" if variables=="donkeypurchased"
replace label="donkeyprice" if variables=="donkeyprice"
replace label="donkeydeath" if variables=="donkeydeath"
replace label="otheliveraised" if variables=="otheliveraised"
replace label="otheliveowned" if variables=="otheliveowned"
replace label="othelivevalue" if variables=="othelivevalue"
replace label="otherliveslau~d" if variables=="otherliveslau~d"
replace label="othelivepurch~d" if variables=="othelivepurch~d"
replace label="otheliveprice" if variables=="otheliveprice"
replace label="othelivedeath" if variables=="othelivedeath"
replace label="Hoe owned" if variables=="prodasset1"
replace label="Hoe value" if variables=="prodassetvalue1"
replace label="Spade asset" if variables=="prodasset2"
replace label="Spade value" if variables=="prodassetvalue2"
replace label="Axe owned" if variables=="prodasset3"
replace label="Axe value" if variables=="prodassetvalue3"
replace label="Sickle owned" if variables=="prodasset4"
replace label="Sickle value" if variables=="prodassetvalue4"
replace label="Shears owned" if variables=="prodasset5"
replace label="Shears value" if variables=="prodassetvalue5"
replace label="Knife owned" if variables=="prodasset6"
replace label="Knife value" if variables=="prodassetvalue6"
replace label="Animal cart owned" if variables=="prodasset7"
replace label="Animal cart value" if variables=="prodassetvalue7"
replace label="Plow/harrow owned" if variables=="prodasset8"
replace label="Plow/harrow value" if variables=="prodassetvalue8"
replace label="Sprayer owned" if variables=="prodasset9"
replace label="Sprayer value" if variables=="prodassetvalue9"
replace label="Water pump owned" if variables=="prodasset10"
replace label="Water pump value" if variables=="prodassetval~10"
replace label="Tractor owned" if variables=="prodasset11"
replace label="Tractor value" if variables=="prodassetval~11"
replace label="persondays hired" if variables=="persondays"
replace label=" Tropical Livestock Unit" if variables=="TLU"
replace label="Average rainfall(mm) in ward for 2014-2018" if variables=="meanrain"
replace label="foodsec    RECODE of foodinsec (foodsecurity)" if variables=="foodsec"
replace label="2 quantiles of HCI" if variables=="HCId"
replace label="               " if variables=="HCIdum"
export excel using "$output\apradescriptive.xls", firstrow(variables) replace
****
use "$data\hhdmerged_", clear
preserve
keep if hh_z_1a == 1
keep interview__id 
save tmp8, replace
restore
keep interview__id hh_a04b1 male hh_z_1a hh_z_2-hh_z_3__21 contrfarming
recode male (0=2), g(gender)
drop male
lab def gender 1 "Male" 2 "Female"
lab val gender gender
tab contrfarming, g(contractf)
drop contractf2 hh_z_1a
order contractf1, before(hh_z_2)
encode interview__id, g(interview__id1)
drop interview__id
order interview__id1
ren interview__id1 interview__id
preserve
keep interview__id hh_a04b1 gender
save tmp9, replace
restore
cap table1 hh_a04b1 gender using $tmp\, id(interview__id) order 
replace label="contract farming" if variables=="hh_z_1a"
replace label="contract years" if variables=="hh_z_2"
replace label="crops contracted:Maize" if variables=="hh_z_3__1"
replace label="crops contracted:Tobacco" if variables=="hh_z_3__2"
replace label="crops contracted:Groundnut" if variables=="hh_z_3__3"
replace label="crops contracted:Wheat" if variables=="hh_z_3__4"
replace label="crops contracted:Barley" if variables=="hh_z_3__5"
replace label="crops contracted:Cowpeas" if variables=="hh_z_3__6"
replace label="crops contracted:Common Beans" if variables=="hh_z_3__7"
replace label="crops contracted:Soya Beans" if variables=="hh_z_3__8"
replace label="crops contracted:Sorghum" if variables=="hh_z_3__9"
replace label="crops contracted:Rice" if variables=="hh_z_3__10"
replace label="crops contracted:Irish Potato" if variables=="hh_z_3__11"
replace label="crops contracted:Sweet Potato" if variables=="hh_z_3__12"
replace label="crops contracted:Onions" if variables=="hh_z_3__13"
replace label="crops contracted:Pepper" if variables=="hh_z_3__14"
replace label="crops contracted:Tomato" if variables=="hh_z_3__15"
replace label="crops contracted:Cabbage" if variables=="hh_z_3__16"
replace label="crops contracted:Butternut" if variables=="hh_z_3__17"
replace label="crops contracted:Vegetables (Covo/Rape)" if variables=="hh_z_3__18"
replace label="crops contracted:Sunflower" if variables=="hh_z_3__21"
export excel using "$output\contract_table1.xls", firstrow(variables) replace
**
use "$data\contractpackage_fin", clear
mer 1:1 interview__id using tmp8
keep if _mer == 3
drop _mer contrfarming
encode interview__id, g(interview__id1)
drop interview__id
order interview__id1
ren interview__id1 interview__id
mer 1:1 interview__id using tmp9
drop _mer
order hh_a04b1 gender
cap table1 hh_a04b1 gender using $tmp\, id(interview__id) order 
replace label="Maize Area" if variables=="hh_z_4a1"
replace label="Tobacco Area" if variables=="hh_z_4a2"
replace label="Soyabeans Area" if variables=="hh_z_4a8"
replace label="Sweet Potato" if variables=="hh_z_4a12"
replace label="Maize under Government of Zimbabwe" if variables=="cont_15"
replace label="Maize under Seedco" if variables=="cont_110"
replace label="Maize under ZLT" if variables=="cont_113"
replace label="Aqua" if variables=="cont_21"
replace label="Boost Africa" if variables=="cont_22"
replace label="CTL" if variables=="cont_23"
replace label="Chidziva Tobacco Processors" if variables=="cont_24"
replace label="Ethical Leaf Tobacco" if variables=="cont_26"
replace label="Mashonaland Tobacco Company" if variables=="cont_27"
replace label="Premier Leaf Tobacco" if variables=="cont_29"
replace label="Shasha Tobacco" if variables=="cont_211"
replace label="Tribac" if variables=="cont_212"
replace label="Zimbabwe Leaf Tobacco" if variables=="cont_213"
replace label="5 cont_8" if variables=="cont_85"
export excel using "$output\contract_table2.xls", firstrow(variables) replace
**

use "$data\hhdmerged_final_analyse", clear
mer 1:1 interview__id using "$data\scheme"
drop _mer
g lnfood = ln(1+foodinsec)
g lnHCI = ln(HCI)
recode foodsec (2 = 0)
lab define foodsec 0 "Food insecure" 1 "Food secure", replace
lab val foodsec foodsec
recode cont_farming1 (1 = 0) (2 = 1)
lab define cont_farming1 0 "No" 1 "Yes", replace
lab val cont_farming1 cont_farming1
**
for var age hhdsize dist meanrain: g lnX = ln(X)
g lnprodval = ln(1+prodval)
eststo: /*qui*/ reg cont_farming1 lnage hh_a_19 female married3 mainjob2 ext1 lnhhdsize /// 
lndist nfarminc lnprodval dpratio lnmeanrain, cluster(farm)
**
eststo: /*qui*/ logit cont_farming1 lnage hh_a_19 female married3 mainjob2 ext1 lnhhdsize /// 
lndist nfarminc lnprodval dpratio lnmeanrain, cluster(farm)
eststo: /*qui*/ margins, dydx(*) post
esttab using "$output\contract_reg.doc", se rtf replace starlevels( * 0.10 ** 0.05 *** 0.010) nodep ///
stats(N r2)  title({\b Table 4:}{Determinants of Contract Farming}) ///
varlabels(lnage "Ln of Age of Household head" hh_a_19 "Years of Schooling of Household head" ///
female  "Female Headed Household" married3 "Head is married monogamously" ///
mainjob2 "Head's main occupation is agriculture" ///
ext1 "Access to extension services" lnhhdsize "Ln Household size" ///
lndist "Ln distance to main markets" nfarminc "Has non-farm income" ///
lnprodval "Ln Value of Productive Assets(US$)" dpratio "Dependency Ratio" ///
lnmeanrain "Ln Average rainfall(mm) in ward for 2014-2018")
eststo clear



